name: Trigger auto deployment for front

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/front-AutoDeployTrigger-aaa3673e-ef86-4f9a-88a1-7e77a044dbce.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FRONT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FRONT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FRONT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.FRONT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FRONT_REGISTRY_PASSWORD }}
          containerAppName: front
          resourceGroup: ebiznes
          imageToBuild: makooo/front:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


